version: '3.8'

services:
  redis:
    image: redis
    container_name: redis
    command: redis-server --requirepass test
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    expose:
      - 6379